const typeMapping = [
    { question: 0, typePositive: ['균형'], typeNegative: ['즉흥'] },
    { question: 1, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 2, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 3, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 4, typePositive: ['집요'], typeNegative: ['즉흥'] },
    { question: 5, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 6, typePositive: ['예민'], typeNegative: ['균형'] },
    { question: 7, typePositive: ['즉흥'], typeNegative: ['예민'] },
    { question: 8, typePositive: ['즉흥'], typeNegative: ['예민'] },
    { question: 9, typePositive: ['즉흥'], typeNegative: ['예민'] },
    { question: 10, typePositive: ['균형'], typeNegative: ['즉흥'] },
    { question: 11, typePositive: ['균형'], typeNegative: ['즉흥'] },
    { question: 12, typePositive: ['즉흥'], typeNegative: ['균형', '집요'] },
    { question: 13, typePositive: ['즉흥'], typeNegative: ['균형'] },
    { question: 14, typePositive: ['예민'], typeNegative: ['균형'] },
    { question: 15, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 16, typePositive: ['즉흥'], typeNegative: ['균형'] },
    { question: 17, typePositive: ['신중'], typeNegative: ['즉흥'] },
    { question: 18, typePositive: ['집요'], typeNegative: ['예민'] },
    { question: 19, typePositive: ['집요'], typeNegative: ['예민'] },
    { question: 20, typePositive: ['균형'], typeNegative: ['집요'] },
    { question: 21, typePositive: ['즉흥'], typeNegative: ['신중'] },
    { question: 22, typePositive: ['집요'], typeNegative: ['신중'] },
    { question: 23, typePositive: ['집요'], typeNegative: ['신중'] },
    { question: 24, typePositive: ['신중'], typeNegative: ['예민'] },
    { question: 25, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 26, typePositive: ['예민'], typeNegative: ['신중'] },
    { question: 27, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 28, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 29, typePositive: ['균형'], typeNegative: ['예민'] },
    { question: 30, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 31, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 32, typePositive: ['신중'], typeNegative: ['예민'] },
    { question: 33, typePositive: ['신중'], typeNegative: ['예민'] },
    { question: 34, typePositive: ['예민'], typeNegative: ['집요'] },
    { question: 35, typePositive: ['예민'], typeNegative: ['균형'] },
    { question: 36, typePositive: ['신중'], typeNegative: ['균형'] },
    { question: 37, typePositive: ['즉흥'], typeNegative: ['예민'] },
    { question: 38, typePositive: ['즉흥'], typeNegative: ['집요', '신중'] },
];

export default typeMapping;
